"""New table position

Revision ID: 7ebe7144ac94
Revises: edcf82b45ae1
Create Date: 2025-03-12 20:48:06.351629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebe7144ac94'
down_revision: Union[str, None] = 'edcf82b45ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(), nullable=False),
    sa.Column('position_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_name')
    )
    op.add_column('cultivators', sa.Column('position_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cultivators', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cultivators', type_='foreignkey')
    op.drop_column('cultivators', 'position_id')
    op.drop_table('positions')
    # ### end Alembic commands ###
