"""Make position_id nullable in cultivators table

Revision ID: 82a4e23b0ef3
Revises: 7ebe7144ac94
Create Date: 2025-03-12 21:07:47.261902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a4e23b0ef3'
down_revision: Union[str, None] = '7ebe7144ac94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cultivators', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cultivators', 'position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
